orbs:
  aws-ecr: circleci/aws-ecr@8.1.2
version: 2.1
parameters:
  alpine-version:
    type: string
    default: "3.15.0"
  image:
    type: string
    default: cimg/base:current
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: org-global
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./
          repo: $CIRCLE_BRANCH/$CIRCLE_PROJECT_REPONAME
          tag: latest,$CIRCLE_SHA1
